[package]
name = "aries_knapsack"
version = "0.1.0"
authors = ["Arthur Bit-Monnot <abitmonnot@laas.fr>"]
edition = "2021"

[dependencies]
aries = { path = "../../solver" }


[[bin]]
name = "aries-knapsack"
path = "main.rs"