[package]
name = "aries_sched"
version = "0.1.0"
authors = ["Arthur Bit-Monnot <abitmonnot@laas.fr>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = { workspace = true }
tracing = { workspace = true }
aries = { path = "../../solver" }
env_param = { path = "../../env_param" }
idmap = { workspace = true }
smallvec = { workspace = true }
