[package]
name = "aries-plan-engine"
version = "0.1.0"
authors = ["Arthur Bit-Monnot <abitmonnot@laas.fr>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
itertools = { workspace = true }
# tracing = { workspace = true }
planx = { path = "../model" }
aries_sched = { path = "../sched" }
aries = { path = "../../solver" }
im = { workspace = true }
# env_param = { path = "../../env_param" }
